server:
  port: 9802
  servlet:
#    encoding:
#      charset: UTF-8
#      enabled: true
#      force: true
    context-path: /


spring:

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    activate:
      on-profile: local
  datasource:
#    hikari:
#      driver-class-name: org.mariadb.jdbc.Driver
#      jdbc-url: jdbc:mariadb://localhost:3308/MEMBERSHIP
#      idle-timeout: 30000         # 커넥션이 풀에서 유휴 상태로 남을 수 있는 최대 시간을 밀리초 단위로 지정한다. 이 값은 minimumIdle이 maximumPoolSize보다 작을 때만 적용된다. 타임아웃이 지난 커넥션을 제거하기까지 최대 30초, 평균 15초 차이 날 수 있다.
#      connection-timeout: 30000   # 풀에서 커넥션을 구할 때 대기 시간을 밀리초 단위로 지정한다. 대기 시간 안에 구하지 못하면 익셉션이 발생한다. 허용 가능한 최소 값은 250이다.
#      validation-timeout: 5000    # 커넥션이 유효한지 검사할 때 대기 시간을 지정한다. 이 값은 connectionTimeout보다 작아야 한다.
#      max-lifetime: 600000        # 10분으로 설정. 커넥션의 최대 유지 시간을 밀리초 단위로 설정한다. 이 시간이 지난 커넥션 중에서 사용중인 커넥션은 종료된 이후에 풀에서 제거한다.
#      username: root
#      password: root
    url: jdbc:mariadb://localhost:3308/MEMBERSHIP
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver



  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    #        open-in-view: false
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      # none : 아무작업안함. , create : 테이블 생성, update : 없으면 생성 있으면 그대로.
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl   # hibernate의 DB Physical Naming 전략에 따라 입력한 그대로 테이블 및 엔티티에 맵핑. 안하면 Spring boot의 전략으로 CamelCase를 snakecase로변환. (@Table에 입력한 그대로 사용)




# log
logging:
  level:
    com: debug
    org:
      springframework: debug
      hibernate:
        type:
          descriptor:
            sql: trace
  config: classpath:logback-spring.xml


# 커스텀 환경변수.
custom:
  service:
    timezone: Asia/Seoul

# 스웨거 request 용 (http://localhost:9801/swagger-ui.html#)
swagger:
  url: localhost:9802